import Head from "next/head";
import { useRouter } from "next/router";
import { names, sidebar } from "../Helper/data";
import SwipeableTemporaryDrawer from "./components/Drawer";

export default function Home() {
  const router = useRouter();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="p-5 bg-[#1d40ae]">
        <div className="flex overflow-hidden ">
          <aside
            id="sidebar"
            className="fixed hidden z-0 h-full top-0 left-0 lg:flex flex-shrink-0 flex-col w-full max-w-md transition-width duration-75"
          >
            <div className="relative flex-1 flex flex-col min-h-0 pt-0">
              <div className="flex-1 flex flex-col pt-5 pb-4 overflow-y-auto">
                <div className="flex-1 pl-3 divide-y space-y-1">
                  <ul className="space-y-2 pb-2">
                    <li className="border-b">
                      <a
                        href="#"
                        className="text-xl font-bold flex items-center lg:ml-2.5"
                      >
                        <span className="text-white my-4  self-center whitespace-nowrap">
                          Thewebvale
                        </span>
                      </a>
                    </li>
                    <li>
                      <form action="#" method="GET" className="lg:hidden">
                        <label htmlFor="mobile-search" className="sr-only">
                          Search
                        </label>
                        <div className="relative">
                          <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                            <svg
                              className="w-5 h-5 text-gray-500"
                              fill="currentColor"
                              viewBox="0 0 20 20"
                              xmlns="http://www.w3.org/2000/svg"
                            >
                              <path d="M5 3a2 2 0 00-2 2v2a2 2 0 002 2h2a2 2 0 002-2V5a2 2 0 00-2-2H5zM5 11a2 2 0 00-2 2v2a2 2 0 002 2h2a2 2 0 002-2v-2a2 2 0 00-2-2H5zM11 5a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2V5zM11 13a2 2 0 012-2h2a2 2 0 012 2v2a2 2 0 01-2 2h-2a2 2 0 01-2-2v-2z"></path>
                            </svg>
                          </div>
                          <input
                            type="text"
                            name="email"
                            id="mobile-search"
                            className="bg-gray-50 font-bold text-gray-900 text-sm rounded-lg focus:ring-cyan-600 focus:ring-cyan-600 block w-full pl-10 p-2.5"
                            placeholder="Search"
                          />
                        </div>
                      </form>
                    </li>
                    {sidebar.map((item) => (
                      <li key={item.name}>
                        <a
                          href="#"
                          className="text-base text-white hover:bg-[#f2f4fa] hover:text-[#1d40ae] font-normal rounded-l-full flex items-center p-2 group"
                        >
                          {item.icon}
                          <span className="ml-3 capitalize">{item.name}</span>
                        </a>
                      </li>
                    ))}
                  </ul>
                  <div className="space-y-2 pt-2">
                    <a
                      href="#"
                      className="text-base text-white hover:bg-[#f2f4fa] hover:text-[#1d40ae] font-normal rounded-l-full flex items-center p-2 group"
                    >
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        className="h-6 w-6 text-white"
                        fill="none"
                        viewBox="0 0 24 24"
                        stroke="currentColor"
                        strokeWidth="2"
                      >
                        <path
                          strokeLinecap="round"
                          strokeLinejoin="round"
                          d="M11 16l-4-4m0 0l4-4m-4 4h14m-5 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h7a3 3 0 013 3v1"
                        />
                      </svg>
                      <span className="ml-4">Logout</span>
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </aside>
          <div className="bg-gray-900 opacity-50 hidden fixed inset-0 z-30"></div>
          <div
            id="main-content"
            className="h-full w-full relative overflow-y-auto lg:ml-64"
          >
            <main>
              <div className="pt-6 pb-1 px-4 rounded-2xl bg-[#f2f4fa]">
                <nav className="mb-4 dark:bg-gray-800">
                  <div className="flex items-center justify-end mt-4 md:mt-0">
                    <div className="hidden relative md:block">
                      <div className="flex absolute inset-y-0 right-3 items-center pl-3 pointer-events-none">
                        <svg
                          className="w-5 h-5 text-gray-500"
                          aria-hidden="true"
                          fill="currentColor"
                          viewBox="0 0 20 20"
                          xmlns="http://www.w3.org/2000/svg"
                        >
                          <path
                            fillRule="evenodd"
                            d="M8 4a4 4 0 100 8 4 4 0 000-8zM2 8a6 6 0 1110.89 3.476l4.817 4.817a1 1 0 01-1.414 1.414l-4.816-4.816A6 6 0 012 8z"
                            clipRule="evenodd"
                          ></path>
                        </svg>
                        <span className="sr-only">Search icon</span>
                      </div>
                      <input
                        type="text"
                        id="search-navbar"
                        className="block p-2 pl-10 w-full text-gray-900 bg-gray-320 rounded-full sm:text-sm focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                      />
                    </div>
                    <button className="hidden mx-4 text-gray-600 transition-colors duration-200 transform md:block dark:text-gray-200 hover:text-gray-700 dark:hover:text-gray-400 focus:text-gray-700 dark:focus:text-gray-400 focus:outline-none">
                      <svg
                        className="w-6 h-6"
                        viewBox="0 0 24 24"
                        fill="none"
                        xmlns="http://www.w3.org/2000/svg"
                      >
                        <path
                          d="M15 17H20L18.5951 15.5951C18.2141 15.2141 18 14.6973 18 14.1585V11C18 8.38757 16.3304 6.16509 14 5.34142V5C14 3.89543 13.1046 3 12 3C10.8954 3 10 3.89543 10 5V5.34142C7.66962 6.16509 6 8.38757 6 11V14.1585C6 14.6973 5.78595 15.2141 5.40493 15.5951L4 17H9M15 17V18C15 19.6569 13.6569 21 12 21C10.3431 21 9 19.6569 9 18V17M15 17H9"
                          stroke="currentColor"
                          strokeWidth="2"
                          strokeLinecap="round"
                          strokeLinejoin="round"
                        />
                      </svg>
                    </button>
                    <button
                      type="button"
                      className="flex items-center focus:outline-none"
                    >
                      <SwipeableTemporaryDrawer />
                    </button>
                  </div>
                </nav>
                <div className="w-full grid grid-cols-1 xl:grid-cols-2 2xl:grid-cols-3 gap-4">
                  <div className="bg-white shadow rounded-lg p-4 sm:p-6 2xl:col-span-2">
                    <div className="w-full grid grid-cols-1 md:grid-cols-2 xl:grid-cols-2 gap-2">
                      <div className="bg-white shadow rounded-lg p-4 sm:p-6">
                        <div className="flex items-center">
                          <div className="flex-shrink-0">
                            <span className="text-2xl sm:text-3xl leading-none font-bold text-gray-900">
                              2,340
                            </span>
                            <h3 className="text-base font-normal text-gray-500">
                              Total Income
                            </h3>
                          </div>
                        </div>
                      </div>
                      <div className="bg-white shadow rounded-lg p-4 sm:p-6">
                        <div className="flex items-center">
                          <div className="flex-shrink-0">
                            <span className="text-2xl sm:text-3xl leading-none font-bold text-gray-900">
                              5,355
                            </span>
                            <h3 className="text-base font-normal text-gray-500">
                              Visitors this week
                            </h3>
                          </div>
                        </div>
                      </div>
                    </div>
                    <button
                      type="button"
                      className="text-white w-full mt-5 bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800"
                    >
                      Recieve
                    </button>
                  </div>
                  <div className="bg-white shadow rounded-lg p-4 sm:p-6 2xl:col-span-2">
                    <div className="flex-shrink-0">
                      <span className="text-base font-bold text-gray-800">
                        Refferal System
                      </span>
                      <h3 className="text-sm w-3/4 font-normal text-gray-500">
                        Earn 10% for direct refferals and 5 % for indirect
                        referrals
                      </h3>
                    </div>
                  </div>
                </div>

                <div className="grid grid-cols-1 2xl:grid-cols-2 xl:gap-4 my-4">
                  <div className="bg-white shadow rounded-lg p-4 sm:p-6">
                    <div className="block w-full overflow-x-auto">
                      <table className="items-center justify-evenly w-full bg-transparent border-collapse">
                        <thead>
                          <tr>
                            <th className="px-4 bg-gray-50 w-1/3 text-gray-700 align-middle py-3 text-xs font-semibold text-left uppercase border-l-0 border-r-0 whitespace-nowrap">
                              ID Number
                            </th>
                            <th className="px-4 bg-gray-50 w-1/3 text-gray-700 align-middle py-3 text-xs font-semibold text-left uppercase border-l-0 border-r-0 whitespace-nowrap">
                              Nickname
                            </th>
                            <th className="px-4 bg-gray-50 w-1/3 text-gray-700 align-middle py-3 text-xs font-semibold text-left uppercase border-l-0 border-r-0 whitespace-nowrap">
                              Registeration time
                            </th>
                          </tr>
                        </thead>
                        <tbody className="divide-y divide-gray-100">
                          {names.map((name, index) => (
                            <tr key={index} className="text-gray-500">
                              <th className="border-t-0 px-4 align-middle text-sm font-normal whitespace-nowrap p-4 text-left">
                                1342314
                              </th>
                              <td className="border-t-0 capitalize px-4 align-middle text-xs font-medium text-gray-900 whitespace-nowrap p-4">
                                {name.name}
                              </td>
                              <td className="border-t-0 px-4 text-xs whitespace-nowrap p-4">
                                <div className="flex items-center">
                                  <span className="mr-2 text-xs font-medium">
                                    5 Oct 2022 - 10:30:30
                                  </span>
                                </div>
                              </td>
                            </tr>
                          ))}
                        </tbody>
                      </table>

                      <ul className="mt-4 w-full flex justify-center items-center">
                        <li>
                          <a
                            href="#"
                            className="block py-2 px-3 ml-0 leading-tight text-gray-500 bg-white rounded-l-lg font-bold hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white"
                          >
                            <span className="sr-only">Previous</span>
                            <svg
                              aria-hidden="true"
                              className="w-5 h-5"
                              fill="currentColor"
                              viewBox="0 0 20 20"
                              xmlns="http://www.w3.org/2000/svg"
                            >
                              <path
                                fillRule="evenodd"
                                d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z"
                                clipRule="evenodd"
                              ></path>
                            </svg>
                          </a>
                        </li>
                        <li>
                          <a
                            href="#"
                            className="py-2 px-3 leading-tight text-gray-500 bg-white font-bold hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white"
                          >
                            1
                          </a>
                        </li>
                        <li>
                          <a
                            href="#"
                            className="py-2 px-3 leading-tight text-gray-500 bg-white font-bold hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white"
                          >
                            2
                          </a>
                        </li>
                        <li>
                          <a
                            href="#"
                            aria-current="page"
                            className="z-10 py-2 px-3 leading-tight bg-blue-600 rounded-full text-gray-50 border border-blue-300 hover:bg-blue-100 hover:text-blue-700 dark:border-gray-700 dark:bg-gray-700 dark:text-white"
                          >
                            3
                          </a>
                        </li>
                        <li>
                          <a
                            href="#"
                            className="py-2 px-3 leading-tight text-gray-500 bg-white font-bold hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white"
                          >
                            4
                          </a>
                        </li>
                        <li>
                          <a
                            href="#"
                            className="py-2 px-3 leading-tight text-gray-500 bg-white font-bold hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white"
                          >
                            5
                          </a>
                        </li>
                        <li>
                          <a
                            href="#"
                            className="block py-2 px-3 leading-tight text-gray-500 bg-white rounded-r-lg font-bold hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white"
                          >
                            <span className="sr-only">Next</span>
                            <svg
                              aria-hidden="true"
                              className="w-5 h-5"
                              fill="currentColor"
                              viewBox="0 0 20 20"
                              xmlns="http://www.w3.org/2000/svg"
                            >
                              <path
                                fillRule="evenodd"
                                d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
                                clipRule="evenodd"
                              ></path>
                            </svg>
                          </a>
                        </li>
                      </ul>
                    </div>
                  </div>

                  <p className="text-center text-sm text-gray-500">
                    &copy; 2019-2021
                    <a href="#" className="hover:underline" target="_blank">
                      Thewebvale
                    </a>
                    . All rights reserved.
                  </p>
                </div>
              </div>
            </main>
          </div>
        </div>
      </div>
    </div>
  );
}
